language: node_js
node_js:
- '5.6'
services:
- mongodb
notifications:
  hipchat:
    rooms:
      secure: AMyrecFfwmfNgSjUeeDFR3fHAmD13b5btTrmk7yKojJOVg8kKGb1dE2u3UpW91g2QVj4XGAmGbPvpdaCwbUaMWKqYsmkX0HdxHL9yro9OSU5h9abes+2a3vLHP3bfoINhTS4tEkFDYu8Mc1UuKTbicoA1ttdGDEhbQ7hQj7P/YnFqX0C1yDTFh6GjYgyGB3xSjQJoj2ZsUwjdB0QlbyR4SUK9eYY6z8aeG9nfQI5Pf0VhC73y7o9blAIhZ+tQxicY0+QuVVmYNSKT/GYFRC4lYD+P3E3PPeNnNqz48SRaw8CwgxImHeijBghsiybSmGLDZsvGfvM/jgUummN/7BRLtUyYFRIQZkOBJzXf2g3wtfYLMQG3yQLxzKWHhjX8WD+qi6+HpvkVu9tzSlY2ug+kp9ou39kULRKYEk8TvEnGlyKIcPAH4qU18TPBm/aNlSoP0xDwTwQyW0fT1BZoePXNE5gKtXxhfyA/tP6y6KjlmzBOzKVLTvMsPjn8hyrWCayw100bkMIbImQAEbFGn4JyXbg7qexFcHcAeHg4KPJ5XROsTXgP7hjxEamnFAS1FQICUpOohVsXOnv6ZTnwBAz5GVzgrsK4t9qd02kKegbRORUME6oHcd6aLVLT7ZFDAfD4hL2Xm5Utt63cHh1+hANdvuOA2t4f5giv0MLD30XNhw=
