language: node_js
node_js:
- '0.10'
services:
- mongodb
notifications:
  hipchat:
    rooms:
      secure: jGv6Orzvef10ztMARs2orDAqPa0Uq2UhLU1ucHql1cFY2cYD0RqdVZBA6oUfOHbRh5N8jLli3inUyIxhiqcbMQUxZ/9NItd8BMTU2FoWvFqiX91rwpy2Qb3A3pO7to0FA3l5yhBlWjPlVxTsg0uFA3eS9sj1sd2MHaR+6PJnCAk=
