language: node_js
node_js:
- '0.10'
services:
- mongodb
notifications:
  hipchat:
    rooms:
      secure: N2kTt4ErNsWEd58A1EuRL15QXwolGMsj6olENcOB/bupdJRdIVK4TCBRZxo6KSEmoTZ5QMhFUSIST9UFYZhZBxgUGW46oLCOYAaPsarjXI/furf01c3xIceUJubUcXQH1rMIaNmRuOZXQpsp4tU0OoMpODIc8Zhk1WctTaRGsqg=
